### ISSUE TITLE
how to use org.wso2.carbon.device.mgt.api in pom.xml maven

### ISSUE THREAD

**Issue by pedy711** [wso2/carbon-device-mgt#1128]
I want to add org.wso2.carbon.device.mgt.api version 3.0.183 and use its classes in my project, but can't add it as a dependency in my pom.xml because it contains no jar file and it is only war and pom file. How can I add it as a dependency in pom.xml?

Other APIs are ok. Like: org.wso2.carbon.policy.mgt.core
I used them as below:

		<dependency>
    		<groupId>org.wso2.carbon.devicemgt</groupId>
    		<artifactId>org.wso2.carbon.policy.mgt.core</artifactId>
    		<version>${carbon.device.mgt.version}</version>
		</dependency>

**Comment by rasika** [comment]
The artifact packaging of the **org.wso2.carbon.device.mgt.api** is a WAR file and it has a dependency on **org.wso2.carbon.policy.mgt.core**. If both artifacts available during runtime; it should work.
