### ISSUE TITLE
IoTs register user - page title issue

### ISSUE THREAD

**Issue by susinda** [wso2/carbon-device-mgt#643]
https://localhost:9443/devicemgt/register - Page title shows as Register | CDMF
Need to be corrected accordingly

**Comment by susinda** [comment]
Same need to be changed for https://localhost:9443/devicemgt/devices
Which shows the title as Device Management | CDMF

**Comment by Kamidu** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt/pull/656
