### ISSUE TITLE
Issues with users created from - Create new Account

### ISSUE THREAD

**Issue by susinda** [wso2/carbon-device-mgt#646]
Users created as in $subject does not show a role associated with them, but if device enrollment is there it shows that user has an enrolment
![iots-2017-03-16 11-10-32](https://cloud.githubusercontent.com/assets/4962136/23983338/737d0934-0a39-11e7-95a2-2a2538b31d08.png)

**Comment by Kamidu** [comment]
@susinda  This is because the users created using the create account/register page does not have any roles other than the internal roles added by the system those internal roles are not listed here. This is the expected view for a user.
So can you please close this issue.
Thanks and Best Regards,

**Comment by susinda** [comment]
Close as per above comment by Kamindu
