### ISSUE TITLE
Device Statistics goes to a error page

### ISSUE THREAD

**Issue by susinda** [wso2/carbon-device-mgt#652]
https://localhost:9443/portal/t/carbon.super/dashboards/device-statistics-dashboard/
The above page shows error,

Following links works fine if manually navigate
https://localhost:9443/portal/t/carbon.super/dashboards/
https://localhost:9443/portal/dashboards/

**Comment by sinthuja** [comment]
How did you come across this URI - https://localhost:9443/portal/t/carbon.super/dashboards/device-statistics-dashboard/? 

Actually, for super tenant resources, we don't need the /t/ in the URI. It would be better if you could provide some steps to reproduce this issue.

**Comment by harshanL** [comment]
Closing the issue as per the above comment by Sinthuja.
