### ISSUE TITLE
pluggable push framework 。How to replace the other push framework？

### ISSUE THREAD

**Issue by wangtyonly** [wso2/carbon-device-mgt#697]

**Comment by ayyoob** [comment]
There are 3 steps that needs to be done to add a new push notification provider

1) Create a provider by implementing the interface - https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt/org.wso2.carbon.device.mgt.common/src/main/java/org/wso2/carbon/device/mgt/common/push/notification/PushNotificationProvider.java

As a reference implementation, You can check https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt-extensions/org.wso2.carbon.device.mgt.extensions.push.notification.provider.fcm/src/main/java/org/wso2/carbon/device/mgt/extensions/push/notification/provider/fcm/FCMBasedPushNotificationProvider.java

2) Add the push notification reference to the cdm-config.xml 
https://github.com/wso2/carbon-device-mgt/blob/master/features/device-mgt/org.wso2.carbon.device.mgt.server.feature/src/main/resources/conf/cdm-config.xml#L29

3) Create a reference to the device type definition by passing the necessary configuration for push notification providers, eg : https://github.com/wso2/carbon-device-mgt-plugins/blob/master/features/device-types-feature/raspberrypi-plugin-feature/org.wso2.carbon.device.mgt.iot.raspberrypi.feature/src/main/resources/devicetypes/raspberrypi.xml#L37-L45
docs: https://docs.wso2.com/display/IoTS300/Server+Communicating+with+the+Device

**Comment by wangtyonly** [comment]
TKS！

**Comment by rasika** [comment]
Please re-open if you need further details on this.
