### ISSUE TITLE
Improve Performance and Reliability of Push notifications service

### ISSUE THREAD

**Issue by warunalakshitha** [wso2/carbon-device-mgt#712]
After sending push notifications to bulk operations, all devices will try to contact server. this will cause high load in server. Need to have scheduler approach to solve this

**Comment by warunalakshitha** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt/pull/725,https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/78

**Comment by warunalakshitha** [comment]
This will add scheduler task for push notification. Please new following new configurations as well.Scheduler task will be enabled by default and need to disable in worker nodes.
`<PushNotificationConfiguration>
    <SchedulerBatchSize>1000</SchedulerBatchSize>
    <SchedulerBatchDelayMills>60000</SchedulerBatchDelayMills>
    <SchedulerTaskInitialDelay>60000</SchedulerTaskInitialDelay>
    <SchedulerTaskEnabled>true</SchedulerTaskEnabled>
    <PushNotificationProviders>
        <Provider>org.wso2.carbon.device.mgt.extensions.push.notification.provider.fcm.FCMBasedPushNotificationProvider</Provider>
        
        <Provider>org.wso2.carbon.device.mgt.extensions.push.notification.provider.mqtt.MQTTBasedPushNotificationProvider</Provider>
        <Provider>org.wso2.carbon.device.mgt.extensions.push.notification.provider.xmpp.XMPPBasedPushNotificationProvider</Provider>
    </PushNotificationProviders>
</PushNotificationConfiguration>`

**Comment by harshanL** [comment]
Closing the issue as per the above comment.
