### ISSUE TITLE
core device mgt with case sensitive issue with postgreSQL.

### ISSUE THREAD

**Issue by thomsonimjd** [wso2/carbon-device-mgt#758]
I have configured the wso2 iot server 3.0.0 with postgreSQL.  Everything works fine while enrolling a new device, except the dm_group table. dm_group table makes an exception saying ID does not exist while enrolling a new device.  Please see the following screen captures of error and the database info.
![image](https://cloud.githubusercontent.com/assets/19526937/26713008/df8d691c-4787-11e7-8e4f-302ec08c39e6.png)
![image](https://cloud.githubusercontent.com/assets/19526937/26713010/e3f8fa70-4787-11e7-844e-4f38894185c2.png)

The error occurs only due to this file 
https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/dao/impl/GroupDAOImpl.java The 50th line makes such exception.  Could you please help me out on this.?

**Comment by thomsonimjd** [comment]
please anyone provide solution for this issue.

**Comment by harshanL** [comment]
This issue has been fixed.
