### ISSUE TITLE
Dynamic-web-client registration

### ISSUE THREAD

**Issue by blissmen** [wso2/carbon-device-mgt#766]
Command I Ran : 

> C:\Users\Admin>curl -k -H "Content-Type: application/json" -X POST -d '{"applicationType":"device","callbackUrl":"","clientName":"353007060797097","grantType":"password refresh_token","owner":"admin","tokenScope":"production"}' https://localhost:9443/dynamic-client-web/register

I Get this as OutPut 
`<html><head><title>Apache Tomcat/7.0.70 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - Servlet execution threw an exception</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Servlet execution threw an exception</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre></p><p><b>root cause</b> <pre>java.lang.NoSuchMethodError: javax.ws.rs.InternalServerErrorException.validate(Ljavax/ws/rs/core/Response;Ljavax/ws/rs/core/Response$Status;)Ljavax/ws/rs/core/Response;
	javax.ws.rs.InternalServerErrorException.&lt;init&gt;(InternalServerErrorException.java:92)
	org.apache.cxf.jaxrs.utils.SpecExceptions.toInternalServerErrorException(SpecExceptions.java:77)
	org.apache.cxf.jaxrs.utils.ExceptionUtils.toInternalServerErrorException(ExceptionUtils.java:110)
	org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.convertExceptionToResponseIfPossible(JAXRSInInterceptor.java:267)
	org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:256)
	org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:88)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.70 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.70</h3></body></html>`

**Comment by geethkokila** [comment]
We are not using this web application anymore. It is being replaced by "api-application-registration" web application.
