### ISSUE TITLE
Get devices by owner with LIKE operator

### ISSUE THREAD

**Issue by Vishanth** [wso2/carbon-device-mgt#767]
When getting the enrolled devices of a user, we are checking the owner name with the LIKE operator. Therefore if there is a device enrolled with owner as "usertwentytwo", this device is also listed to the user "usertwenty".

https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/dao/impl/device/GenericDeviceDAOImpl.java#L98

**Comment by harshanL** [comment]
This issue has been fixed by adding a new query param to use with like operator.
