### ISSUE TITLE
Device listing issue with case insensitive user login

### ISSUE THREAD

**Issue by Vishanth** [wso2/carbon-device-mgt#768]
When case insensitive the user is allowed to login with simple and capital case. For instance, when the user logs in with simple case username and enrolls a device and when he logs in again with camel case or uppercase, then the device is not listed.

We should retrieve devices by owner case insensitively. 

https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt/org.wso2.carbon.device.mgt.core/src/main/java/org/wso2/carbon/device/mgt/core/dao/impl/device/GenericDeviceDAOImpl.java#L98

**Comment by harshanL** [comment]
Closing the issue as it's resolved in above commits.
